package rothschild.henning.jacob.noriginmedia.controller;

import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;

/**
 * A {@link FragmentPagerAdapter} that returns a fragment corresponding to
 * one of the sections/tabs/pages.
 *
 * Auto-generated by Android Studio.
 *
 * Can be thought of as the controller of the tab-functionality.
 */
public class SectionsPagerAdapter extends FragmentPagerAdapter {
	
	public SectionsPagerAdapter(FragmentManager fm) {
		super(fm);
	}
	
	@Override
	public Fragment getItem(int position) {
		return position == 2 ? new EPGFragment() : PlaceholderFragment.newInstance(position + 1);
	}
	
	@Override
	public int getCount() {
		// Show 5 pages
		return 5;
	}
	
	@Override
	public CharSequence getPageTitle(int position) {
		return "SECTION " + (position + 1);
	}
	
	public boolean isTouchesAllowed(int position) {
		// If touches are allowed in the tab with epg the ViewPager will overpower the epg, making it unscrollable. Otherwise, we enjoy the ViewPager-scroll
		return position != 2;
	}
}